services:
  docker-node:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app # host:container
      - node_modules:/usr/local/lib/node_modules
      - usr_local_share:/usr/local/share/
    ports:
      - "5173:5173" # host:container
    env_file:
      - .env
    command: >
      bash -c "npm i && npm dev"

volumes:
  node_modules:
  usr_local_share:
