services:
  docker-node:
    container_name: docker-node
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - node_modules:/usr/local/lib/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    command: >
      bash -c "npm i && npm run dev:docker"

volumes:
  node_modules:
